colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

mainSections = ["game-interaction", "writing-research", "other-projects"]

[homepage]
  layout = "background"
  homepageImage = "img/home-background.png"
  showRecent = true
  showRecentItems = 40
  layoutBackgroundBlur = false

[header]
  layout = "basic"

[list]
  showSummary = true
  showTableOfContents = true

[article]
 showDate = true
 showReadingTime = true
 showWordCount = true
 showTableOfContents = true
 showTaxonomies = true
 showTags = true